json file questions uploading during application startup
AkademiaProgramowania/interview-master pull request #13
Opened 2024-01-27 11:27 UTC by Hodon534

2nd try

2024-02-04 13:11 UTC, Sora-nya commented
Żeby to zmergować, musisz najpierw wyrównać się do mastera i rozwiązać konflikty :)

2024-02-04 13:12 UTC, Sora-nya requested changes

2024-02-04 13:12 UTC, Sora-nya commented on src/main/java/pl/pop/interview/master/question/QuestionUploader.java
> + * Class responsible for populating questions from a JSON file into the database.
Ten komentarz z kolei jest bardzo spoko, bo opisuje co ma robić co nie jest widoczne na pierwszy rzut oka.

2024-02-04 13:12 UTC, Sora-nya commented on src/main/java/pl/pop/interview/master/question/QuestionUploaderConfig.java
> + * Configuration class responsible for initializing data population during application startup.
Redundantne komentarze, patrz w mapperCongfig.

2024-02-05 21:27 UTC, DrJul requested changes
Dwa testy odnoszą się jeszcze do nieistniejącej klasy Enum YesNo -> Crtl + Shift + F i wpisz nazwę tej klasy to Ci wyszuka po projekcie. Przed wysłaniem kodu trzeba sprawdzić czy się kompiluje i testy przechodzą lokalnie, a jeśli nie to trzeba spojrzeć na GithubAcitions czy jest na zielono

2024-02-05 21:27 UTC, DrJul commented on src/main/java/pl/pop/interview/master/question/QuestionUploader.java
> +    private ObjectMapper objectMapper;
dodać "final" po private (dla obu pól)

2024-02-05 21:27 UTC, DrJul commented on src/main/java/pl/pop/interview/master/global/MapperConfig.java
> +package pl.pop.interview.master.global;
zmieniłbym nazwę pakietu na "config"

2024-02-06 22:37 UTC, DrJul requested changes
1) 2 komentarze dodane
2) pojawiły się konflikty do rozwiązania

2024-02-06 22:37 UTC, DrJul commented on src/main/java/pl/pop/interview/master/question/QuestionDTO.java
> +    public QuestionDTO(Long id, String content, String correctAnswer) {
poprzedni konstruktor z dwoma paramterami można usunąć

2024-02-06 22:37 UTC, DrJul commented on src/test/java/pl/pop/interview/master/answer/AnswerServiceTest.java
> +        Question question1 = new Question("Question1Content", "Yes");
ogólnie spoko ale na przyszłość: osobiście jakbym już miał to poprawiać to bym zrobił stałe w polach
 private final String YES = "Yes" (analogicznie dla "No") i ich użył w testach zamiast wszędzie Stringa pisać z ręki

2024-02-06 23:12 UTC, closed without merging