15 refactor ddd
AkademiaProgramowania/interview-master pull request #14
Opened 2024-01-27 15:22 UTC by fngs101

Zrobiłam fasady + serwisy które je implementują. Zmieniłam ich nazwy na ...Manager, żeby wskazywały czym się zajmują te implementacje. 

Wszystko co było możliwe jest package private, oprócz Practitionera - potrzebny jest w domenie account. Wywalanie go do jakiejś paczki "shared" jakoś mi nie pasowało więc zostawiłam public. Nie bardzo wiem co z nim uczynić. 🤔 

Pozwoliłam sobie posprzątać trochę użycie lomboka (wyrzuciłam manualne gettery i settery, zamiast @Getter i @Setter -> @Data)

Co do testów - jeśli kierować się tym co Nabdralik sugeruje testy powinny być chyba napisane bez Mockito a w zamian użycie map. Jeśli chcemy tak samo to powinien być chyba na to osobny task + każde kolejne testy powinny być w ten sposób pisane. Ale to już do rozważenia osobno.

2024-02-04 13:45 UTC, Sora-nya commented
Po pierwsze, rozwiąż konflikty, bo teraz nie da się tego zmergować: @fngs101

2024-02-04 19:11 UTC, fngs101 commented
Rozwiązane. 
Wszystko co pisałam wcześniej wciąż valid i do przemyślenia, możliwe że na forum grupy będzie lepiej to przedyskutować? Nie wiem

2024-02-05 23:16 UTC, DrJul requested changes
1) @Data może powodować problemy - odnośnik w komentarzu
2) Implementacje Practitionera zostawiamy jak zrobiłaś, bo temat trzeba omówić w grupie i najwyżej się wystawi nowy ticket
3) testy bym robił normalnie z Mockito ponieważ: uczymy się, TDD nikt raczej nie stosuje tutaj ;), performace testów jest w tej chwili dla nas drugorzędny. Sam temat jednak ciekawy i jak najbardziej do poruszenia

2024-02-05 23:16 UTC, DrJul commented on src/main/java/pl/pop/interview/master/account/Account.java
> +@Data
hej, niestety adnotacja @Data jest niepożądana. Może powodować problemy przy porównywaniu obiektów bo nadpisuje hascode i equalsa. Lepiej wrócić do osobnych adnotacji, tylko tych ktróych potrzebujemy

2024-02-05 23:16 UTC, DrJul commented on src/main/java/pl/pop/interview/master/account/Account.java
> +@Data
https://dzone.com/articles/lombok-and-jpa-what-may-go-wrong

2024-02-06 15:03 UTC, fngs101 commented
Faktycznie doczytałam, trochę za bardzo pobiegłam z tym data, nie zważając n JPA. 
Co do testów i Practitionera - ok, pewnie będziemy to jeszcze przegadywać. :) 
Dzięki!

2024-02-06 21:52 UTC, DrJul approved these changes

2024-02-06 21:59 UTC, merged