#19 - transition from String to boolean for "yes/no" questions
AkademiaProgramowania/interview-master pull request #18
Opened 2024-02-09 09:53 UTC by Hodon534

#19 - transition from String to boolean for "yes/no" questions

2024-02-09 13:54 UTC, AkademiaProgramowania requested changes
Myląca nazwa w AnswerDTO

2024-02-09 13:54 UTC, AkademiaProgramowania commented on src/main/java/pl/pop/interview/master/answer/AnswerDTO.java
> +    private boolean isCorrect;
bardzo myląca nazwa.
nie wiadomo czy to jest treść odpowiedzi na pytanie: tak lub nie czy komentarz systemu czy nasza odpowiedź była poprawna czy nie. 
Zostałbym przy nazwie answer mimo że to boolean

2024-02-09 22:30 UTC, cogunites reviewed
raczej kosmetyki. 
Ale fajnie by było gdyby to poszło

Kamil

2024-02-09 22:30 UTC, cogunites commented on src/main/java/pl/pop/interview/master/answer/AnswerManager.java
> +    public AnswerDTO save(Long questionId, boolean isTrue) {
skoro wyżej, tj. w DTO, została zmieniona nazwa z "isCorrect" na "answer", to tutaj też może być tak nazwane. 
Wtedy będzie jaśniej informowało co z tym się dzieje.

2024-02-09 22:30 UTC, cogunites commented on src/main/java/pl/pop/interview/master/question/Question.java
> +    private boolean correctAnswer;
Tutaj, też bym pomyślał nad tym czy na pewno "correctAnswer" jest potrzebne, skoro to jest pytanie i raczej "answer" by samo w sobie informowało, że jest to poprawna odpowiedź.

2024-02-09 22:30 UTC, cogunites commented on src/main/java/pl/pop/interview/master/question/Question.java
> +    public Question(String content, boolean correctAnswer) {
to samo tutaj. Raczej bym poszedł w kierunku "answer".

2024-02-09 22:30 UTC, cogunites commented on src/main/java/pl/pop/interview/master/question/QuestionDTO.java
> +    private boolean correctAnswer;
i tutaj i w linii 24.

2024-02-10 12:00 UTC, dixu11 commented
W takim puszczam jak Kamil sugeruje.  Hodon fajnie jakbyś później zgłosił pull requesta jeszcze z refactorem nazw :)

2024-02-10 12:00 UTC, merged